services:
  api:
    container_name: urlshortener_service
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port ${DEVELOPMENT_SERVER_PORT} --reload
    volumes:
      - ./src:/app/src
    ports:
      - ${DEVELOPMENT_SERVER_PORT}:${DEVELOPMENT_SERVER_PORT}

    depends_on:
      - db
    env_file:
        - .env
  db:
    container_name: urshortener_db
    image: postgis/postgis:13-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}


volumes:
  postgres_data:
